name: knowit_ly
description: KnowIt is an educational and entertaining app that provides valuable sexual health information through a fun puzzle game. It is designed to make learning about sexual health topics accessible and enjoyable for users.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.1

  # state management
  flutter_riverpod: ^2.1.1

  # urls
  url_launcher: ^6.1.6

  # fonts
  google_fonts: ^3.0.1

  # navigation
  go_router: ^6.0.1

  # firebase


  # images
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2

  # extras
  flextras: ^1.0.0
  sliver_tools: ^0.2.8

  # animations
  animations: ^2.0.7

  # sharing
  share_plus: ^6.2.0 

  # puzzle related packages
  tuple: ^2.0.1
  freezed_annotation: ^2.2.0
  animated_text_kit: ^4.2.2
  wave: ^0.2.2
  intl: ^0.18.0

  flutter_fortune_wheel: ^1.2.0
  confetti: ^0.7.0

  # splash
  flutter_native_splash: ^2.2.16


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.11.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/